runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: yaml
  version: "3.10"
- name: pycrypto
  version: "2.6"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always
- url: /public
  static_dir: public
  secure: always
- url: /.*
  script: lib.app.router
  secure: always

skip_files:
- ^node_modules
